<!DOCTYPE html>
<html>
<head>
    <title>About Us</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 20px;
        }
        nav {
            background-color: #333; /* Цвет фона навигационного меню */
            padding: 10px;
            color: #fff; /* Цвет текста в навигационном меню */
        }

        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }

        nav ul li {
            float: left;
        }

        nav ul li a {
            display: block;
            padding: 10px 20px;
            color: #fff; /* Цвет текста в ссылках навигационного меню */
            text-decoration: none;
        }

        nav ul li a:hover {
            background-color: #555; /* Цвет фона при наведении на ссылку */
        }


        h1 {
            color: #333;
            text-align: center;
        }

        p {
            color: #666;
            line-height: 1.5;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
<nav>
    <ul>
        <li><a href="/">Main page</a></li>
        <li><a href="/about">About Us</a></li>
        <li><a href="/contact">Contact</a></li>
    </ul>
</nav>
<h1>About Us</h1>
<p>Welcome to LinguaVista, a leading language school specializing in immersive language learning experiences. At LinguaVista, we believe that language acquisition is not just about memorizing vocabulary and grammar rules, but about immersing oneself in the language and culture. Our mission is to provide students with the tools and opportunities to become confident and proficient language speakers.</p>
<p>Our experienced team of language instructors are passionate about teaching and dedicated to creating dynamic and engaging learning environments. We offer a wide range of language courses tailored to different proficiency levels and learning objectives. Whether you are a beginner or an advanced learner, we have a course that suits your needs.</p>
<p>In addition to our language courses, we also organize cultural events, language exchanges, and study trips to further enhance the language learning experience. These activities provide students with the opportunity to practice their language skills in real-life contexts and connect with other language enthusiasts.</p>
<p>Join us at LinguaVista and embark on a journey of language discovery. Let us guide you in achieving your language learning goals and explore the richness of different cultures through language.</p>
</body>
</html>
