<!DOCTYPE html>
<html>
<head>
    <title>Contacts</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 20px;
        }

        h1 {
            color: #333;
            text-align: center;
        }

        .contact-info {
            margin-bottom: 20px;
        }

        .contact-info b {
            font-weight: bold;
        }

        .contact-info span {
            display: block;
            margin-top: 5px;
        }
    </style>
</head>
<body>
<h1>Contacts</h1>
<div class="contact-info">
    <b>Address:</b>
    <span>Chuy street 74</span>
    <span>Bishkek, Kyrgyzstan</span>
    <span>Postal Code: 720001</span>
</div>
<div class="contact-info">
    <b>Email:</b>
    <span>lingua_vista@yandex.com</span>
</div>
<div class="contact-info">
    <b>Phone:</b>
    <span>++996550586266</span>
</div>
<div class="contact-info">
    <b>Working Hours:</b>
    <span>Monday-Friday: 9:00 AM - 5:00 PM</span>
    <span>Saturday: 10:00 AM - 2:00 PM</span>
</div>
<div class="contact-info">
    <b>Social Media:</b>
    <span>Facebook: <a href="https://www.facebook.com/profile.php?id=100092336091480">https://www.facebook.com/profile.php?id=100092336091480</a></span>
</div>
</body>
</html>
