<!DOCTYPE html>
<html>
<head>
    <title>Contacts</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            margin: 0;
            padding: 20px;
        }

        h1 {
            color: #333;
            text-align: center;
        }

        .contact-info {
            margin-bottom: 20px;
        }

        .contact-info b {
            font-weight: bold;
        }

        .contact-info span {
            display: block;
            margin-top: 5px;
        }
        nav {
            background-color: #333; /* Цвет фона навигационного меню */
            padding: 10px;
            color: #fff; /* Цвет текста в навигационном меню */
        }

        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
        }

        nav ul li {
            float: left;
        }

        nav ul li a {
            display: block;
            padding: 10px 20px;
            color: #fff; /* Цвет текста в ссылках навигационного меню */
            text-decoration: none;
        }

        nav ul li a:hover {
            background-color: #555; /* Цвет фона при наведении на ссылку */
        }
    </style>
</head>
<body>
<nav>
    <ul>
        <li><a href="/">Main page</a></li>
        <li><a href="/about">About Us</a></li>
        <li><a href="/contact">Contact</a></li>
    </ul>
</nav>
<h1>Contacts</h1>
<div class="contact-info">
    <b>Address:</b>
    <span>Chuy street 74</span>
    <span>Bishkek, Kyrgyzstan</span>
    <span>Postal Code: 720001</span>
</div>
<div class="contact-info">
    <b>Email:</b>
    <span>lingua_vista@yandex.com</span>
</div>
<div class="contact-info">
    <b>Phone:</b>
    <span>++996550586266</span>
</div>
<div class="contact-info">
    <b>Working Hours:</b>
    <span>Monday-Friday: 9:00 AM - 5:00 PM</span>
    <span>Saturday: 10:00 AM - 2:00 PM</span>
</div>
<div class="contact-info">
    <b>Social Media:</b>
    <span>Facebook: <a href="https://www.facebook.com/profile.php?id=100092336091480">https://www.facebook.com/profile.php?id=100092336091480</a></span>
</div>
</body>
</html>
